### ISSUE TITLE
Contents of included file is corrupted

### ISSUE THREAD

**Issue by tulumbas** [jbdemonte/gulp-file-insert#3]
Since the contents of an included file is insert with a `string.replace()`, it is subject of substitution of special characters. E.g. if I'm injecting js code which contains $$, $1 and so on, they will be changed accordingly to some unexpected values.

**Comment by jbdemonte** [comment]
Can you provide an example?

**Comment by threeset3** [comment]
@jbdemonte Can confirm. For example, some file with the content 

> Hello
> $$
> How are you

Will be inserted as

> Hello
> $
> How are you

**Comment by threeset3** [comment]
Created pull request #4

**Comment by dayvidwhy** [comment]
@jbdemonte any word on merging this in? Solves an issue I was having with including giant files, would prefer to not have to keep manually including @threeset3 's fix.

**Comment by jbdemonte** [comment]
sorry, I forgot that PR...
